In [2]:
import numpy as np

# Creating arrays

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.full(5, 6)

array([6, 6, 6, 6, 6])

In [10]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [11]:
a[2]

3

In [12]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multidimensional arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
n[0][1]

2

In [25]:
n[0][1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
n[0]

array([ 1, 20,  3])

In [28]:
n[1]

array([4, 5, 6])

In [29]:
n[1] = np.ones(3)

In [30]:
n

array([[ 1, 20,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

In [31]:
n[:, 1] # get the column index = 1

array([20,  1,  8])

In [32]:
n[:, 1] = [0,1,2]
n

array([[1, 0, 3],
       [1, 1, 1],
       [7, 2, 9]])

# Randomly generated arrays

In [37]:
np.random.rand(5,2)

array([[0.54254437, 0.14217005],
       [0.37334076, 0.67413362],
       [0.44183317, 0.43401399],
       [0.61776698, 0.51313824],
       [0.65039718, 0.60103895]])

In [39]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [40]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [41]:
100 * np.random.rand(5,2)

array([[62.11338328, 52.91420943],
       [13.45799453, 51.35781213],
       [18.44398656, 78.53351478],
       [85.39752926, 49.42368374],
       [84.65614854,  7.9645477 ]])

In [42]:
np.random.randint(0,100,(5,2))

array([[68, 46],
       [70, 95],
       [83, 31],
       [66, 80],
       [52, 76]])

# Element-wise operations

In [51]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [52]:
a + 1 

array([1, 2, 3, 4, 5])

In [53]:
b = 10 + (b * 100)
b

array([ 10, 110, 210, 310, 410])

In [54]:
a + b

array([ 10, 111, 212, 313, 414])

## Comparison operations

In [55]:
a

array([0, 1, 2, 3, 4])

In [57]:
a >= 2

array([False, False,  True,  True,  True])

In [58]:
b

array([ 10, 110, 210, 310, 410])

In [59]:
a > b 

array([False, False, False, False, False])

In [60]:
a[a > b]

array([], dtype=int64)

In [61]:
a[a < b]

array([0, 1, 2, 3, 4])

# Summarizing operations

In [62]:
arr = a

In [66]:
min_value = arr.min()    # Minimum value
max_value = arr.max()    # Maximum value
sum_value = arr.sum()    # Sum of all elements
mean_value = arr.mean()  # Mean (average) value
std_deviation = arr.std()  # Standard deviation

min_value, max_value,sum_value

(0, 4, 10)